### PR TITLE
fix: blur slider input on change

### LINKED ISSUE #279: Spacebar Doesn't Pause Simulation After Clicking Speed Selector
After clicking the speed selector slider, pressing the spacebar no longer pauses or resumes the simulation. It seems the slider component captures focus and prevents the global key listener from working as expected.

### PR DESCRIPTION
**Pull request by pgallino**
closes #279

### CODE REVIEW

File: src/graphics/basic_components/slider.ts [hunk 1]
```diff
@@ -42,6 +42,7 @@ export class Slider {
       if (props.onChange) {
         props.onChange(value);
       }
+      this.sliderInput.blur();
```
Comment (MegaRedHand) [inline src/graphics/basic_components/slider.ts:45]: This fixes cases where the user moves the slider, but not the ones where the user just clicks on the slider. For that, we probably need to add the same on the onclick handler.

**Review by MegaRedHand — APPROVED** [review]
