### PR TITLE
fix: Save canvas position

### LINKED ISSUE #92: Save current position on local storage
If we move on the view a bit before building the network, it might appear as it disappeared once we reload.

### PR DESCRIPTION
**Pull request by V-SANT**
This pull request enhances viewport management in the GlobalContext and Viewport classes by adding support for saving, restoring, and centering the view.

### On code
- GlobalContext: Added restorePosition and centerView to manage viewport state.

- Viewport: Implemented methods to save/restore position and zoom, and to set the center.

- viewportManager.ts: Automatically centers the viewport after loading a file.

### On functionalities
- The viewport's position and zoom now persist after reloading.
- Pressing the "New" button centers the viewport in the middle of the canvas.
- Loading a graph from a file centers the viewport on the graph's centroid (Similar to a center of mass of a particle system).

## Known Bugs and Enhancements
- Pressing the "New" or "Load" buttons updates the layer in the selector, but not in the left sidebar, causing inconsistencies in the UI.
- The canvas boundaries are not visually indicated, which can be problematic when building a network near the edges without realizing you've reached the limit.

#### Before pressing new 
image

#### Afther pressing new
image

#### Before load
image

#### After load
image

On both cases, the link layer is selected but the left bar only shows hosts

Closes #92

### CODE REVIEW

File: src/graphics/viewport.ts [hunk 1]
```diff
@@ -28,47 +28,82 @@ export class Viewport extends pixi_viewport.Viewport {
...
+  // Restore the saved position of the viewport
+  public restorePosition() {
+    const savedPosition = localStorage.getItem("viewportPosition");
+    const savedZoom = localStorage.getItem("viewportZoom");
+
+    if (savedPosition) {
+      const { x, y } = JSON.parse(savedPosition);
+      this.position.set(x, y);
+    } else {
+      this.position.set(WORLD_WIDTH / 2, WORLD_HEIGHT / 2);
```
Comment (MegaRedHand) [inline src/graphics/viewport.ts:84]: Should we use `setCenter` here?

**Comment by MegaRedHand** [comment]
The position is not being saved or loaded.

File: src/graphics/viewport.ts (hunk 1 above)
Comment (V-SANT) [reply src/graphics/viewport.ts:84]: We can, but we should send the center calculation on ctx. 
This function restores the same position and zoom before refresh which are saved on localStorage. If the simulator is used for the first time, the default position is on the center of the world with zoom 1.

**Review by MegaRedHand — APPROVED** [review]
